# Generated by Django 3.2 on 2023-04-22 16:59

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Google', 'Google'), ('Instagram', 'YouTube')], max_length=100, verbose_name='Организация')),
                ('email', models.EmailField(max_length=70, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Organization_defaulr_wt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateField(auto_created=True, verbose_name='Время выхода')),
                ('start_time', models.DateField(auto_created=True, verbose_name='Время посешение')),
                ('name', models.CharField(max_length=70, verbose_name=mainapp.models.Organizations)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120, verbose_name='Имя')),
                ('last_name', models.TextField(max_length=120, verbose_name='Фамилия')),
                ('organizations', models.CharField(max_length=70)),
                ('passvord', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(max_length=70, verbose_name='Имя')),
                ('name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('organizations', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
            },
        ),
        migrations.CreateModel(
            name='Work_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateField(auto_created=True)),
                ('start_time', models.DateField(auto_created=True)),
                ('user', models.TextField()),
                ('organizations', models.TextField()),
            ],
        ),
    ]
